# builds the content of:
# * https://github.com/symplify/phpstan-rules

# inspired by https://raw.githubusercontent.com/symplify/symplify/38d5929624d0ceb47d25d97ab020d685ac7b39a5/.github/workflows/downgrade_packages.yaml

name: Downgraded Release

on:
    push:
        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

jobs:
    downgrade_release:
        runs-on: ubuntu-latest

        steps:
            -
                uses: "actions/checkout@v2"

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            # 3. downgrade directly
            -   run: vendor/bin/rector process src --config build/config/rector-downgrade.php --ansi
            -   run: vendor/bin/ecs check src --ansi

            # copy metafiles to repository as well
            -   run: cp build/target-repository/composer.json composer.json
            -   run: rm -rf build .github tests stubs ecs.php phpstan.neon phpunit.xml

            # setup git user
            -
                run: |
                    git config user.email "action@github.com"
                    git config user.name "GitHub Action"

            # publish it to local repository to new branch with a tag
            -
                name: "Tag Downgraded Code"
                run: |
                    git commit -a -m "release PHP 7.2 downgraded ${GITHUB_REF#refs/tags/}"
                    git tag "${GITHUB_REF#refs/tags/}.72"
                    git push origin "${GITHUB_REF#refs/tags/}.72"
